-- เพิ่มตารางวันหยุดพิเศษที่ Admin สามารถเพิ่ม/แก้ไข/ลบได้รายเดือน
CREATE TABLE IF NOT EXISTS public.special_holidays (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_id bigint NOT NULL REFERENCES public.duty_months(id) ON DELETE CASCADE,
    holiday_date date NOT NULL,
    holiday_name text NOT NULL DEFAULT 'วันหยุดพิเศษ',
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT special_holidays_month_date_unique UNIQUE (month_id, holiday_date)
);

CREATE INDEX IF NOT EXISTS idx_special_holidays_month_id
ON public.special_holidays(month_id);

CREATE INDEX IF NOT EXISTS idx_special_holidays_date
ON public.special_holidays(holiday_date);

-- ตรวจสอบ
SELECT id, month_id, holiday_date, holiday_name
FROM public.special_holidays
ORDER BY month_id, holiday_date;
